 # Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build Angular App and publish artifacts
    jobs:
      - job: BuildAngularApp
        displayName: Build Angular App
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
            npm install -g @angular/cli
            npm install puppeteer --save-dev
          displayName: 'Install the angular cli globally'

        - task: Npm@1
          inputs:
            command: 'install'
          displayName: 'Install angular app packages'

        - task: Npm@1
          displayName: 'Build Angular application'
          inputs:
            command: custom
            customCommand: run build -- --prod

          # ...
          # do this after other tasks such as building
        - task: DotNetCoreCLI@2
          inputs:
            command: test
            projects: '**/*Tests/*.csproj'
            arguments: '--configuration $(buildConfiguration)'
        
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            testResultsFiles: '**/TEST-*.xml'
          displayName: 'Publish Test Results'
        
        - task: PublishBuildArtifacts@1
          displayName: Publish Angular app dist folder artifact
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'angular-app'
            publishLocation: 'Container'
